EPMRPP-93073 migrate to JDK21
reportportal/commons-reporting pull request #14
Opened 2024-11-07 09:16 UTC by grabsefx

* JDK21
* gradle 8.10.2
* latest libraries versions
* junit 5
* lombok

2024-11-11 08:18 UTC, pbortnik approved these changes

2024-11-11 08:19 UTC, APiankouski approved these changes

2025-01-03 10:27 UTC, HardNorth requested changes

2025-01-03 10:27 UTC, HardNorth commented on build.gradle
> +        api "org.springdoc:springdoc-openapi-starter-common:${springDocVersion}"
I didn't manage to find any single reference on Spring in the code. If don use this library only to include transient Swagger annotations, please remove it and include `swagger-annotations` directly.

2025-01-03 10:27 UTC, HardNorth commented on build.gradle
> +        api "com.fasterxml.jackson.core:jackson-databind:${jacksonVersion}"
We don't want our users rely on jackson version specified by our library, since we want to be free changing it. Please revert to `implementation`.

2025-01-03 10:27 UTC, HardNorth commented on build.gradle
> +        api "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:${jacksonVersion}"
Same as for `jackson-databind`.

2025-01-03 10:34 UTC, grabsefx commented on jitpack.yml
> +  - openjdk21
the project already migrate to JDK 21
https://github.com/reportportal/commons-reporting/blob/develop/build.gradle#L38

2025-01-03 10:42 UTC, grabsefx commented on build.gradle
> +        api "org.springdoc:springdoc-openapi-starter-common:${springDocVersion}"
fixed

2025-01-03 10:42 UTC, grabsefx commented on build.gradle
> +        api "com.fasterxml.jackson.core:jackson-databind:${jacksonVersion}"
fixed

2025-01-03 10:42 UTC, grabsefx commented on build.gradle
> +        api "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:${jacksonVersion}"
fixed

2025-01-03 11:16 UTC, HardNorth commented on jitpack.yml
> +  - openjdk21
The fact that I missed this, is not an excuse.

2025-01-13 11:15 UTC, pbortnik requested changes
Postponed till java version decision

2025-01-24 13:46 UTC, HardNorth approved these changes
Approved, as discussed

2025-01-27 13:15 UTC, pbortnik approved these changes

2025-01-28 15:54 UTC, merged